SET FOREIGN_KEY_CHECKS=0;
SET AUTOCOMMIT = 0;

DROP TABLE Species IF EXISTS;
DROP TABLE Whales IF EXISTS;
DROP TABLE Sightings_Whales IF EXISTS;
DROP TABLE Researchers IF EXISTS;
DROP TABLE Sightings IF EXISTS;
DROP TABLE Organizations IF EXISTS;


SET FOREIGN_KEY_CHECKS=1;
COMMIT;